## Este notebook se crea con el fin de llevara acabo el modelo de datos espaciales

#### Creado por Alexander Duarte V
##### 26/03/23

In [ ]:
Api : AIzaSyAAZmD7wE13UcW5w9OQVQkAZrrEfpTaP9o

### cargar paquetes a usar

In [1]:
import pandas as pd
import os

In [2]:
# Obtener una lista de nombres de archivos y carpetas en el directorio actual
archivos_y_carpetas = os.listdir()

# Imprimir los nombres de los archivos y carpetas en el directorio actual
print("Archivos y carpetas en el directorio actual:")
for archivo_o_carpeta in archivos_y_carpetas:
    print(archivo_o_carpeta)

Archivos y carpetas en el directorio actual:
.git
.gitattributes
.gitignore
.ipynb_checkpoints
.RData
.Rhistory
.Rproj.user
Analisis_info.ipynb
enlaces_descarga.txt
IPM.xlsx
modelo_datos_espaciales.R
poblacion.csv
Proyecto Cundinamarca.Rproj
README.md
Untitled1.ipynb

### cargar los datos de población

In [3]:
poblacion = pd.read_csv('poblacion.csv', dtype={'MPIO': str, 'AÑO': str, 'DP': str})
poblacion.head(10)

,DP,DPNOM,DPMP,MPIO,AÑO,ÁREA GEOGRÁFICA,Hombres_0,Hombres_1,Hombres_2,Hombres_3,...,Total_79,Total_80,Total_81,Total_82,Total_83,Total_84,Total_85 y más,Total Hombres,Total Mujeres,Total General
0,05,Antioquia,Medellín,05001,2005,Cabecera Municipal,13812,14233,14680,15148,...,4352,3944,3547,3132,2776,2540,12870,927942,1069821,1997763
1,05,Antioquia,Medellín,05001,2005,Centros Poblados y Rural Disperso,489,493,499,503,...,83,76,67,60,52,48,231,23924,24654,48578
2,05,Antioquia,Medellín,05001,2005,Total,14301,14726,15179,15651,...,4435,4020,3614,3192,2828,2588,13101,951866,1094475,2046341
3,05,Antioquia,Medellín,05001,2006,Cabecera Municipal,13674,14001,14411,14868,...,4490,4098,3700,3310,2909,2556,13663,941723,1084305,2026028
4,05,Antioquia,Medellín,05001,2006,Centros Poblados y Rural Disperso,475,475,478,483,...,83,77,68,61,54,47,229,23716,24451,48167
5,05,Antioquia,Medellín,05001,2006,Total,14149,14476,14889,15351,...,4573,4175,3768,3371,2963,2603,13892,965439,1108756,2074195
6,05,Antioquia,Medellín,05001,2007,Cabecera Municipal,13469,13869,14195,14606,...,4640,4226,3844,3449,3075,2675,14414,955438,1098528,2053966
7,05,Antioquia,Medellín,05001,2007,Centros Poblados y Rural Disperso,457,459,462,465,...,85,77,70,62,56,50,239,23526,24279,47805
8,05,Antioquia,Medellín,05001,2007,Total,13926,14328,14657,15071,...,4725,4303,3914,3511,3131,2725,14653,978964,1122807,2101771
9,05,Antioquia,Medellín,05001,2008,Cabecera Municipal,13308,13679,14063,14392,...,4736,4354,3956,3576,3201,2827,15236,969223,1112673,2081896

In [4]:
poblacion.columns

Index(['DP', 'DPNOM', 'DPMP', 'MPIO', 'AÑO', 'ÁREA GEOGRÁFICA', 'Hombres_0',
       'Hombres_1', 'Hombres_2', 'Hombres_3',
       ...
       'Total_79', 'Total_80', 'Total_81', 'Total_82', 'Total_83', 'Total_84',
       'Total_85 y más', 'Total Hombres', 'Total Mujeres', 'Total General'],
      dtype='object', length=267)

In [5]:
## ajustar la información 
f_poblacion = poblacion.loc[(poblacion['DP'].isin(['11', '25'])) & (poblacion['AÑO'].isin(['2018', '2005']))]

f_poblacion.head (10)

,DP,DPNOM,DPMP,MPIO,AÑO,ÁREA GEOGRÁFICA,Hombres_0,Hombres_1,Hombres_2,Hombres_3,...,Total_79,Total_80,Total_81,Total_82,Total_83,Total_84,Total_85 y más,Total Hombres,Total Mujeres,Total General
6660,11,"Bogotá, D.C.","Bogotá, D.C.",11001,2005,Cabecera Municipal,58915,59654,60503,61422,...,10272,9330,8373,7435,6505,5912,29097,3228140,3466554,6694694
6661,11,"Bogotá, D.C.","Bogotá, D.C.",11001,2005,Centros Poblados y Rural Disperso,216,218,219,222,...,15,12,10,9,6,5,17,8337,7879,16216
6662,11,"Bogotá, D.C.","Bogotá, D.C.",11001,2005,Total,59131,59872,60722,61644,...,10287,9342,8383,7444,6511,5917,29114,3236477,3474433,6710910
6699,11,"Bogotá, D.C.","Bogotá, D.C.",11001,2018,Cabecera Municipal,48847,48580,48323,48094,...,17019,15345,13801,12380,11077,9881,63141,3531374,3856026,7387400
6700,11,"Bogotá, D.C.","Bogotá, D.C.",11001,2018,Centros Poblados y Rural Disperso,263,260,257,255,...,37,31,26,21,15,13,61,12704,12462,25166
6701,11,"Bogotá, D.C.","Bogotá, D.C.",11001,2018,Total,49110,48840,48580,48349,...,17056,15376,13827,12401,11092,9894,63202,3544078,3868488,7412566
20610,25,Cundinamarca,Agua de Dios,25001,2005,Cabecera Municipal,40,42,46,49,...,49,45,42,37,33,29,185,3420,3964,7384
20611,25,Cundinamarca,Agua de Dios,25001,2005,Centros Poblados y Rural Disperso,20,20,20,22,...,14,13,11,11,11,10,57,1245,1188,2433
20612,25,Cundinamarca,Agua de Dios,25001,2005,Total,60,62,66,71,...,63,58,53,48,44,39,242,4665,5152,9817
20649,25,Cundinamarca,Agua de Dios,25001,2018,Cabecera Municipal,45,45,45,46,...,61,59,53,50,45,42,269,4279,4834,9113

In [6]:
# Crear una nueva columna con la suma de la población de niños (0 a 14 años)
f_poblacion['Niños_M'] = f_poblacion.loc[:, 'Hombres_0':'Hombres_14'].sum(axis=1)

# Crear una nueva columna con la suma de la población de jóvenes (15 a 29 años)
f_poblacion['Jóvenes_M'] = f_poblacion.loc[:, 'Hombres_15':'Hombres_29'].sum(axis=1)

# Crear una nueva columna con la suma de la población de adultos (30 a 59 años)
f_poblacion['Adultos_M'] = f_poblacion.loc[:, 'Hombres_30':'Hombres_59'].sum(axis=1)

# Crear una nueva columna con la suma de la población de adultos mayores (60 años o más)
f_poblacion['Adultos mayores_M'] = f_poblacion.loc[:, 'Hombres_60':'Hombres_85 y más'].sum(axis=1)

# Crear una nueva columna con la suma de la población de niños (0 a 14 años)
f_poblacion['Niñas'] = f_poblacion.loc[:, 'Mujeres_0':'Mujeres_14'].sum(axis=1)

# Crear una nueva columna con la suma de la población de jóvenes (15 a 29 años)
f_poblacion['Jóvenes_F'] = f_poblacion.loc[:, 'Mujeres_15':'Mujeres_29'].sum(axis=1)

# Crear una nueva columna con la suma de la población de adultos (30 a 59 años)
f_poblacion['Adultos_F'] = f_poblacion.loc[:, 'Mujeres_30':'Mujeres_59'].sum(axis=1)

# Crear una nueva columna con la suma de la población de adultos mayores (60 años o más)
f_poblacion['Adultos mayores_F'] = f_poblacion.loc[:, 'Mujeres_60' :'Mujeres_85 y más'].sum(axis=1)

C:\Users\DELL\AppData\Local\Temp\ipykernel_33636\3140972596.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f_poblacion['Niños_M'] = f_poblacion.loc[:, 'Hombres_0':'Hombres_14'].sum(axis=1)
C:\Users\DELL\AppData\Local\Temp\ipykernel_33636\3140972596.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f_poblacion['Jóvenes_M'] = f_poblacion.loc[:, 'Hombres_15':'Hombres_29'].sum(axis=1)
C:\Users\DELL\AppData\Local\Temp\ipykernel_33636\3140972596.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f_poblacion['Adultos_M'] = f_poblacion.loc[:, 'Hombres_30':'Hombres_59'].sum(axis=1)
C:\Users\DELL\AppData\Local\Temp\ipykernel_33636\3140972596.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f_poblacion['Adultos mayores_M'] = f_poblacion.loc[:, 'Hombres_60':'Hombres_85 y más'].sum(axis=1)
C:\Users\DELL\AppData\Local\Temp\ipykernel_33636\3140972596.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f_poblacion['Niñas'] = f_poblacion.loc[:, 'Mujeres_0':'Mujeres_14'].sum(axis=1)
C:\Users\DELL\AppData\Local\Temp\ipykernel_33636\3140972596.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f_poblacion['Jóvenes_F'] = f_poblacion.loc[:, 'Mujeres_15':'Mujeres_29'].sum(axis=1)
C:\Users\DELL\AppData\Local\Temp\ipykernel_33636\3140972596.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f_poblacion['Adultos_F'] = f_poblacion.loc[:, 'Mujeres_30':'Mujeres_59'].sum(axis=1)
C:\Users\DELL\AppData\Local\Temp\ipykernel_33636\3140972596.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f_poblacion['Adultos mayores_F'] = f_poblacion.loc[:, 'Mujeres_60' :'Mujeres_85 y más'].sum(axis=1)

In [7]:
f_poblacion_grupos = f_poblacion.loc[:, ['DP', 'DPNOM', 'DPMP', 'MPIO', 'AÑO', 'ÁREA GEOGRÁFICA', 
                                           'Niños_M', 'Jóvenes_M', 'Adultos_M', 'Adultos mayores_M', 
                                           'Niñas', 'Jóvenes_F', 'Adultos_F', 'Adultos mayores_F', 
                                         'Total Hombres', 'Total Mujeres', 'Total General']]

In [8]:
f_poblacion_grupos = f_poblacion_grupos.rename(columns={'ÁREA GEOGRÁFICA': 'area',
                                                         'Total Hombres': 'Total_Hombres',
                                                         'Total Mujeres': 'Total_Mujeres',
                                                         'Total General': 'Total_General'})

In [9]:
f_poblacion_grupos['area'] = f_poblacion_grupos['area'].replace({'Cabecera Municipal': 'urbano', 
                                                                 'Centros Poblados y Rural Disperso': 'rural', 
                                                                 'Total': 'total'})

In [10]:
f_poblacion_grupos.head (4)

,DP,DPNOM,DPMP,MPIO,AÑO,area,Niños_M,Jóvenes_M,Adultos_M,Adultos mayores_M,Niñas,Jóvenes_F,Adultos_F,Adultos mayores_F,Total_Hombres,Total_Mujeres,Total_General
6660,11,"Bogotá, D.C.","Bogotá, D.C.",11001,2005,urbano,979683,888661,1141809,217987,931873,918089,1328405,288187,3228140,3466554,6694694
6661,11,"Bogotá, D.C.","Bogotá, D.C.",11001,2005,rural,3370,2021,2471,475,3151,1905,2408,415,8337,7879,16216
6662,11,"Bogotá, D.C.","Bogotá, D.C.",11001,2005,total,983053,890682,1144280,218462,935024,919994,1330813,288602,3236477,3474433,6710910
6699,11,"Bogotá, D.C.","Bogotá, D.C.",11001,2018,urbano,730639,984097,1418534,398104,703354,989774,1616909,545989,3531374,3856026,7387400

In [11]:
# Guardar el DataFrame en formato CSV
f_poblacion_grupos.to_csv('poblacion_bogota_cundinamarca.csv', index=False)

# Guardar metadatos en un archivo de texto
with open('metadatos_p.txt', 'a') as f:
    f.write('--- Información del archivo poblacion_bogota_cundinamarca.csv ---\n')
    f.write('Este archivo contiene información de la población por grupos de edad y género para los años 2005 y 2018, discriminada por género, para Bogotá y el departamento de Cundinamarca.\n')
    f.write('Las columnas son: DP, DPNOM, DPMP, MPIO, AÑO, area, Niños_M, Jóvenes_M, Adultos_M, Adultos mayores_M, Niñas, Jóvenes_F, Adultos_F, Adultos mayores_F, Total_Hombres, Total_Mujeres y Total_General.')

In [12]:
# Cargar el archivo CSV y almacenarlo en un DataFrame
poblacion_cun = pd.read_csv('poblacion_bogota_cundinamarca.csv', dtype={'MPIO': str, 'AÑO': str, 'DP': str})
poblacion_cun.head (10)

,DP,DPNOM,DPMP,MPIO,AÑO,area,Niños_M,Jóvenes_M,Adultos_M,Adultos mayores_M,Niñas,Jóvenes_F,Adultos_F,Adultos mayores_F,Total_Hombres,Total_Mujeres,Total_General
0,11,"Bogotá, D.C.","Bogotá, D.C.",11001,2005,urbano,979683,888661,1141809,217987,931873,918089,1328405,288187,3228140,3466554,6694694
1,11,"Bogotá, D.C.","Bogotá, D.C.",11001,2005,rural,3370,2021,2471,475,3151,1905,2408,415,8337,7879,16216
2,11,"Bogotá, D.C.","Bogotá, D.C.",11001,2005,total,983053,890682,1144280,218462,935024,919994,1330813,288602,3236477,3474433,6710910
3,11,"Bogotá, D.C.","Bogotá, D.C.",11001,2018,urbano,730639,984097,1418534,398104,703354,989774,1616909,545989,3531374,3856026,7387400
4,11,"Bogotá, D.C.","Bogotá, D.C.",11001,2018,rural,3690,3224,4519,1271,3649,3115,4495,1203,12704,12462,25166
5,11,"Bogotá, D.C.","Bogotá, D.C.",11001,2018,total,734329,987321,1423053,399375,707003,992889,1621404,547192,3544078,3868488,7412566
6,25,Cundinamarca,Agua de Dios,25001,2005,urbano,852,621,1145,802,846,727,1501,890,3420,3964,7384
7,25,Cundinamarca,Agua de Dios,25001,2005,rural,332,208,427,278,326,225,424,213,1245,1188,2433
8,25,Cundinamarca,Agua de Dios,25001,2005,total,1184,829,1572,1080,1172,952,1925,1103,4665,5152,9817
9,25,Cundinamarca,Agua de Dios,25001,2018,urbano,794,852,1536,1097,730,883,1865,1356,4279,4834,9113

### cargar datos socioeconomicos de los municipios IPM

In [13]:
# Leer el archivo "IPM.xlsx"

# Cargar el archivo Excel sin utilizar la primera fila como encabezados de columna
ipm = pd.read_excel('IPM.xlsx', dtype={'cod_mpio': str, 'Año': str, 'dp': str})

# Imprimir las primeras 10 filas del DataFrame resultante
ipm.head(10)

,dp,cod_mpio,Municipio,Año,Analfabetismo,Bajo logro educativo,Barreras a servicios para cuidado de la primera infancia,Barreras de acceso a servicios de salud,Tasa de dependecia económica\n,Hacinamiento crítico,Inadecuada eliminación de excretas,Inasistencia escolar,Material inadecuado de paredes exteriores,Material inadecuado de pisos,Rezago escolar,Sin acceso a fuente de agua mejorada,Sin aseguramiento en salud,Trabajo infantil,Trabajo informal
0,11,11001,BOGOTA,2018,2.8,26.2,1.8,4.3,18.9,5.6,0.7,1.9,0.3,0.3,11.5,0.5,18.7,0.5,69.1
1,25,25001,AGUA DE DIOS,2018,9.6,55.7,0.9,1.2,33.2,7.8,3.4,1.8,1.2,2.6,9.2,3.9,12.0,0.4,80.2
2,25,25019,ALBAN,2018,9.8,65.0,0.9,9.5,29.0,4.6,5.7,2.1,1.9,2.5,16.5,16.8,13.3,0.6,79.5
3,25,25035,ANAPOIMA,2018,9.2,58.9,1.4,4.2,21.9,7.9,6.6,2.1,5.4,4.5,14.5,23.2,13.6,1.2,77.3
4,25,25040,ANOLAIMA,2018,14.1,67.9,1.5,3.1,27.3,5.3,8.9,2.0,3.3,5.7,11.9,12.1,12.2,0.9,85.6
5,25,25053,ARBELAEZ,2018,8.2,60.1,1.3,1.8,25.7,6.2,4.4,3.6,1.9,5.6,16.0,11.4,12.0,1.5,84.0
6,25,25086,BELTRAN,2018,18.9,74.8,0.6,1.5,48.1,6.7,7.9,1.7,0.9,4.4,17.1,20.0,12.5,0.8,78.9
7,25,25095,BITUIMA,2018,16.9,78.4,0.7,0.2,26.4,3.7,9.5,2.7,1.1,8.1,13.5,27.8,12.6,1.3,86.1
8,25,25099,BOJACA,2018,7.3,52.7,1.8,9.0,20.9,8.8,1.5,2.5,0.9,0.8,18.4,5.4,16.2,1.1,70.0
9,25,25120,CABRERA,2018,11.7,72.1,1.0,4.5,28.6,7.6,8.9,3.2,1.4,2.8,16.1,61.3,13.0,4.5,93.1

In [14]:


# Renombrar las columnas del DataFrame
ipm = ipm.rename(columns={
    'Municipio': 'mpio',
    'Analfabetismo': 'Analfabetismo ',
    'Bajo logro educativo': 'Bajo_logro_educativo',
    'Inasistencia escolar': 'Inasistencia_escolar',
    'Rezago escolar': 'Rezago_escolar',
    'Barreras a servicios para cuidado de la primera infancia': 'barreras_primera_infancia',
    'Trabajo infantil': 'Trabajo_infantil',
    'Tasa de dependecia económica\n': 'dependencia_económica',
    'Trabajo informal': 'Empleo_informal',
    'Sin aseguramiento en salud': 'Sin_salud',
    'Barreras de acceso a servicios de salud': 'Barreras_salud',
    'Sin acceso a fuente de agua mejorada': 'Sin_acceso_agua_mejorada',
    'Inadecuada eliminación de excretas': 'Inadecuada_elim_excretas',
    'Material inadecuado de pisos': 'Pisos_inadecuados',
    'Material inadecuado de paredes exteriores': 'Paredes_inadecuadas',
    'Hacinamiento crítico': 'Hacinamiento'
})


# Convertir los nombres de columna a minúsculas y reemplazar espacios por guiones bajos
ipm.columns = ipm.columns.str.lower().str.replace(' ', '_')

# Imprimir las primeras 10 filas del DataFrame resultante
ipm.head(10)

,dp,cod_mpio,mpio,año,analfabetismo_,bajo_logro_educativo,barreras_primera_infancia,barreras_salud,dependencia_económica,hacinamiento,inadecuada_elim_excretas,inasistencia_escolar,paredes_inadecuadas,pisos_inadecuados,rezago_escolar,sin_acceso_agua_mejorada,sin_salud,trabajo_infantil,empleo_informal
0,11,11001,BOGOTA,2018,2.8,26.2,1.8,4.3,18.9,5.6,0.7,1.9,0.3,0.3,11.5,0.5,18.7,0.5,69.1
1,25,25001,AGUA DE DIOS,2018,9.6,55.7,0.9,1.2,33.2,7.8,3.4,1.8,1.2,2.6,9.2,3.9,12.0,0.4,80.2
2,25,25019,ALBAN,2018,9.8,65.0,0.9,9.5,29.0,4.6,5.7,2.1,1.9,2.5,16.5,16.8,13.3,0.6,79.5
3,25,25035,ANAPOIMA,2018,9.2,58.9,1.4,4.2,21.9,7.9,6.6,2.1,5.4,4.5,14.5,23.2,13.6,1.2,77.3
4,25,25040,ANOLAIMA,2018,14.1,67.9,1.5,3.1,27.3,5.3,8.9,2.0,3.3,5.7,11.9,12.1,12.2,0.9,85.6
5,25,25053,ARBELAEZ,2018,8.2,60.1,1.3,1.8,25.7,6.2,4.4,3.6,1.9,5.6,16.0,11.4,12.0,1.5,84.0
6,25,25086,BELTRAN,2018,18.9,74.8,0.6,1.5,48.1,6.7,7.9,1.7,0.9,4.4,17.1,20.0,12.5,0.8,78.9
7,25,25095,BITUIMA,2018,16.9,78.4,0.7,0.2,26.4,3.7,9.5,2.7,1.1,8.1,13.5,27.8,12.6,1.3,86.1
8,25,25099,BOJACA,2018,7.3,52.7,1.8,9.0,20.9,8.8,1.5,2.5,0.9,0.8,18.4,5.4,16.2,1.1,70.0
9,25,25120,CABRERA,2018,11.7,72.1,1.0,4.5,28.6,7.6,8.9,3.2,1.4,2.8,16.1,61.3,13.0,4.5,93.1

In [15]:
# Guardar el DataFrame en formato CSV
ipm.to_csv('ipm_bogota_cundinamarca.csv', index=False)

# Guardar metadatos en un archivo de texto
with open('metadatos_ipm.txt', 'w') as f:
    f.write('--- Información del archivo ipm_bogota_cundinamarca.csv ---\n')
    f.write('Este archivo contiene información del Índice de Pobreza Multidimensional para Bogotá y los municipios de Cundinamarca para los años 2005 y 2018, según datos del DANE.\n')
    f.write('Las columnas son: dp, cod_mpio, mpio, año, numero_hogares, Bajo_logro_educativo, Analfabetismo, Inasistencia_escolar, Rezago_escolar, barreras_primera_infancia, Trabajo_infantil, dependencia_económica, Empleo_informal, Sin_salud, Barreras_salud, Sin_acceso_agua_mejorada, Inadecuada_elim_excretas, Pisos_inadecuados, Paredes_inadecuadas, Hacinamiento.')

In [16]:
# Cargar el archivo CSV y almacenarlo en un DataFrame
ipm = pd.read_csv('ipm_bogota_cundinamarca.csv', dtype={'cod_mpio': str, 'Año': str, 'dp': str})
ipm.head (10)

,dp,cod_mpio,mpio,año,analfabetismo_,bajo_logro_educativo,barreras_primera_infancia,barreras_salud,dependencia_económica,hacinamiento,inadecuada_elim_excretas,inasistencia_escolar,paredes_inadecuadas,pisos_inadecuados,rezago_escolar,sin_acceso_agua_mejorada,sin_salud,trabajo_infantil,empleo_informal
0,11,11001,BOGOTA,2018,2.8,26.2,1.8,4.3,18.9,5.6,0.7,1.9,0.3,0.3,11.5,0.5,18.7,0.5,69.1
1,25,25001,AGUA DE DIOS,2018,9.6,55.7,0.9,1.2,33.2,7.8,3.4,1.8,1.2,2.6,9.2,3.9,12.0,0.4,80.2
2,25,25019,ALBAN,2018,9.8,65.0,0.9,9.5,29.0,4.6,5.7,2.1,1.9,2.5,16.5,16.8,13.3,0.6,79.5
3,25,25035,ANAPOIMA,2018,9.2,58.9,1.4,4.2,21.9,7.9,6.6,2.1,5.4,4.5,14.5,23.2,13.6,1.2,77.3
4,25,25040,ANOLAIMA,2018,14.1,67.9,1.5,3.1,27.3,5.3,8.9,2.0,3.3,5.7,11.9,12.1,12.2,0.9,85.6
5,25,25053,ARBELAEZ,2018,8.2,60.1,1.3,1.8,25.7,6.2,4.4,3.6,1.9,5.6,16.0,11.4,12.0,1.5,84.0
6,25,25086,BELTRAN,2018,18.9,74.8,0.6,1.5,48.1,6.7,7.9,1.7,0.9,4.4,17.1,20.0,12.5,0.8,78.9
7,25,25095,BITUIMA,2018,16.9,78.4,0.7,0.2,26.4,3.7,9.5,2.7,1.1,8.1,13.5,27.8,12.6,1.3,86.1
8,25,25099,BOJACA,2018,7.3,52.7,1.8,9.0,20.9,8.8,1.5,2.5,0.9,0.8,18.4,5.4,16.2,1.1,70.0
9,25,25120,CABRERA,2018,11.7,72.1,1.0,4.5,28.6,7.6,8.9,3.2,1.4,2.8,16.1,61.3,13.0,4.5,93.1

In [1]:
ipm.columns

NameError: name 'ipm' is not defined

### Calcula la accesibilidad o proximidad a Bogotá (distancia al centro de la ciudad o tiempo de viaje) para cada municipio.

In [ ]:
from geopy.geocoders import Nominatim
import time

geolocalizador = Nominatim(user_agent="miGeocoder")

ejemplo_municipios =  [ "Agua de Dios", "Albán", "Anapoima","Anolaima", "Arbeláez", "Beltrán", "Bituima",  "Bojacá", "Cabrera", "Cachipay", "Cajicá",
                           "Caparrapí", "Cáqueza", "Carmen de Carupa", "Chaguaní",  "Chía", "Chipaque", "Choachí", "Chocontá", "Cogua",  "Cota",  "Cucunubá", 
                           "El Colegio", "El Peñón", "El Rosal", "Facatativá", "Fómeque", "Fosca", "Funza", "Fúquene", "Fusagasugá","Gachalá", "Gachancipá",
                           "Gachetá",   "Gama",  "Girardot",  "Granada",  "Guachetá",  "Guaduas",  "Guasca", "Guataquí", "Guatavita", "Guayabal de Síquima",
                           "Guayabetal", "Gutiérrez", "Jerusalén",  "Junín", "La Calera", "La Mesa", "La Palma", "La Peña", "La Vega", "Lenguazaque",  "Machetá",  
                           "Madrid",  "Manta", "Medina", "Mosquera", "Nariño", "Nemocón", "Nilo", "Nimaima", "Nocaima", "Venecia",  "Pacho",  "Paime",  "Pandi",
                           "Paratebueno",  "Pasca", "Puerto Salgar",  "Pulí",  "Quebradanegra",  "Quetame",  "Quipile", "Apulo",  "Ricaurte", 
                           "San Antonio del Tequendama", "San Bernardo",  "San Cayetano", "San Francisco", "San Juan de Rioseco",  "Sasaima",  "Sesquilé",
                           "Sibaté", "Silvania",  "Simijaca","Soacha", "Sopó", "Subachoque", "Suesca", "Supatá",  "Susa", "Sutatausa",  "Tabio", "Tausa",
                           "Tena",  "Tenjo", "Tibacuy", "Tibirita", "Tocaima", "Tocancipá", "Topaipí", "Ubalá",  "Ubaque", "Villa de San Diego de Ubaté", "Une",
                           "Útica",  "Vergara", "Vianí", "Villagómez", "Villapinzón", "Villeta", "Viotá", "Yacopí", "Zipacón","Zipaquirá"     
]

coordenadas_municipios = []

for municipio in ejemplo_municipios:
    ubicacion = None
    while ubicacion is None:
        try:
            ubicacion = geolocalizador.geocode(municipio + ", Cundinamarca, Colombia", timeout=5)
        except:
            time.sleep(1)  # Agrega un retraso de 1 segundo antes de intentarlo nuevamente
    coordenadas = (ubicacion.latitude, ubicacion.longitude)
    coordenadas_municipios.append((municipio, coordenadas))
    time.sleep(1)  # Agrega un retraso de 2 segundo entre cada solicitud para no sobrecargar el servidor

print(coordenadas_municipios)

In [3]:
coordenadas_municipios

[('Agua de Dios', (4.3772853, -74.6694759)),
 ('Albán', (4.8780617, -74.4384462)),
 ('Anapoima', (4.5493011, -74.5359119))]

In [23]:
import googlemaps

# Reemplaza 'YOUR_API_KEY' con tu clave API de Google Maps
api_key = 'AIzaSyAAZmD7wE13UcW5w9OQVQkAZrrEfpTaP9o'

# Crea una instancia del cliente de Google Maps
gmaps = googlemaps.Client(key=api_key)

# Coordenadas del centro de Bogotá (aproximadamente)
bogota_center = (4.60971, -74.08175)

# Crear un DataFrame vacío para almacenar los resultados
resultados = pd.DataFrame(columns=["Municipio", "Distancia", "Tiempo de viaje"])

# Crear la lista de municipios de Cundinamarca y sus coordenadas (aproximadas) a partir de la lista de coordenadas_municipios
municipios = [{"nombre": municipio, "coordenadas": coords} for municipio, coords in coordenadas_municipios]

# Calcula la distancia y el tiempo de viaje desde cada municipio hasta el centro de Bogotá
for municipio in municipios:
    result = gmaps.distance_matrix(origins=municipio["coordenadas"],
                                   destinations=bogota_center,
                                   mode="driving",
                                   units="metric")
    
    distance = result["rows"][0]["elements"][0]["distance"]["text"]
    duration = result["rows"][0]["elements"][0]["duration"]["text"]

    resultados = resultados.append({"Municipio": municipio["nombre"],
                                    "Distancia": distance,
                                    "Tiempo de viaje": duration}, ignore_index=True)

resultados.head(3)

C:\Users\DELL\AppData\Local\Temp\ipykernel_33636\581063512.py:34: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  resultados = resultados.append({"Municipio": municipio["nombre"],
C:\Users\DELL\AppData\Local\Temp\ipykernel_33636\581063512.py:34: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  resultados = resultados.append({"Municipio": municipio["nombre"],
C:\Users\DELL\AppData\Local\Temp\ipykernel_33636\581063512.py:34: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  resultados = resultados.append({"Municipio": municipio["nombre"],

      Municipio Distancia  Tiempo de viaje
0  Agua de Dios    122 km  2 hours 58 mins
1         Albán   59.7 km   1 hour 41 mins
2      Anapoima   86.3 km  2 hours 10 mins

In [ ]:
divipola_codigos = { "Agua de Dios": "25001", "Albán": "25019", "Anapoima": "25035",  "Anolaima": "25040", "Arbeláez": "25053",  "Beltrán": "25086", 
                    "Bituima": "25099", "Bojacá": "25120", "Cabrera": "25123", "Cachipay": "25126", "Cajicá": "25148", "Caparrapí": "25151", "Cáqueza": "25154",
                    "Carmen de Carupa": "25168", "Chaguaní": "25175", "Chía": "25178", "Chipaque": "25181", "Choachí": "25183", "Chocontá": "25185",
                    "Cogua": "25200", "Cota": "25214", "Cucunubá": "25224", "El Colegio": "25245", "El Peñón": "25258", "El Rosal": "25260", "Facatativá": "25269",
                    "Fómeque": "25279", "Fosca": "25281", "Funza": "25286", "Fúquene": "25288", "Fusagasugá": "25290", "Gachalá": "25293", "Gachancipá": "25295",
                    "Gachetá": "25297", "Gama": "25299", "Girardot": "25307", "Granada": "25312", "Guachetá": "25317", "Guaduas": "25320", "Guasca": "25322",
                    "Guataquí": "25324", "Guatavita": "25326", "Guayabal de Síquima": "25328", "Guayabetal": "25335", "Gutiérrez": "25339", "Jerusalén": "25368",
                    "Junín": "25372", "La Calera": "25377", "La Mesa": "25386", "La Palma": "25394","La Peña": "25398", "La Vega": "25402", "Lenguazaque": "25407",
                    "Machetá": "25426",  "Madrid": "25430", "Manta": "25436", "Medina": "25438", "Mosquera": "25473", "Nariño": "25483",  "Nemocón": "25486",
                    "Nilo": "25488", "Nimaima": "25489", "Nocaima": "25491", "Venecia": "25506",  "Pacho": "25513", "Paime": "25518",  "Pandi": "25524",
                    "Paratebueno": "25530", "Pasca": "25535", "Puerto Salgar": "25572", "Pulí": "25580", "Quebradanegra": "25592",  "Quetame": "25594",  
                    "Quipile": "25596",  "Apulo": "25599", "Ricaurte": "25612", "San Antonio del Tequendama": "25645", "San Bernardo": "25649",
                    "San Cayetano": "25653", "San Francisco": "25658", "San Juan de Rioseco": "25662", "Sasaima": "25718","Sesquilé": "25736", "Sibaté": "25740",
                    "Silvania": "25743", "Simijaca": "25745",  "Soacha": "25754",  "Sopó": "25758", "Subachoque": "25764",  "Suesca": "25769",  "Supatá": "25772",
                    "Susa": "25777", "Sutatausa": "25779", "Tabio": "25781", "Tausa": "25785", "Tena": "25793", "Tenjo": "25797", "Tibacuy": "25799",
                    "Tibirita": "25805",  "Tocaima": "25807", "Tocancipá": "25815", "Topaipí": "25817", "Ubalá": "25823", "Ubaque": "25839",
                    "Villa de San Diego de Ubaté": "25841",  "Une": "25843", "Útica": "25845", "Vergara": "25851", "Vianí": "25862", "Villagómez": "25867",
                    "Villapinzón": "25871", "Villeta": "25873","Viotá": "25875", "Yacopí": "25878", "Zipacón": "25885", "Zipaquirá": "25899"
}